apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mongosource
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://https://github.com/Ombi657/flux_mongo